interpolation:
  enabled: y
  fps: 960
  speed: medium
  tuning: smooth
  algorithm: 13
  use gpu: yes
  mask:

frame blending:
  enabled: yes
  fps: 60
  intensity: 1.3
  weighting: gaussian_sym

flowblur:
  enabled: no
  amount: 100
  mask:

encoding:
  process: ffmpeg
  loglevel: error
  args: H264 CPU

preview:
  enabled: no
  ffmpeg: -s 1280x720 -f yuv4mpegpipe -
  process: ffplay
  args: -loglevel quiet -i - -autoexit -window_title smoothie.preview -loglevel quiet

misc:
  mpv bin: mpv
  stay on top: true
  verbose: false
  ding after: 1
  folder: 
  container: .MP4
  prefix: 
  suffix: fruits
  dedupthreshold: 0

console params:
  ontop: yes
  borderless: yes
  width: 900
  height: 35

timescale:
  in: 1.0
  out: 1.0

pre interp:
  enabled: no
  factor: 2x
  model: rife-v4.4
